title: "Security Espresso"
logo: logo-horizontal.png
logo_square: logo.png
email: contact@securityespresso.com
description: Security for developers

url: "https://securityespresso.org" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
github_username:  securityespresso
#twitter_username: jekyllrb

permalink: pretty
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

plugins:
  - jekyll-sitemap
  - jekyll-paginate
