title: "Security Espresso"
logo: logo-horizontal.png
logo_square: logo.png
email: securityespresso@shark0der.com
description: Security for developers

#url: "https://securityespresso.org" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
github_username:  securityespresso
#twitter_username: jekyllrb

permalink: pretty
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Server Config options
livereload: true     # You no longer need to include --livereload

gems:
  - jekyll-sitemap
  - jekyll-paginate
